# Generated by Django 2.0.3 on 2018-04-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180428_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='books',
            field=models.ManyToManyField(to='catalog.Book'),
        ),
    ]
