# Generated by Django 2.0.3 on 2018-05-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180429_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='books',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['x_coor', 'y_coor']},
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
